{"score": 50, "full_score": 100, "tests": {"q1": "PASS (10/10)", "q2": "PASS (10/10)", "q3": "PASS (10/10)", "q4": "PASS (10/10)", "q5": "PASS (10/10)", "q6": ["Traceback (most recent call last):\n", "  File \"/home/atrej/p2-a-team/tester.py\", line 28, in run\n    result = self.func()\n", "  File \"/home/atrej/p2-a-team/autograde.py\", line 102, in q6\n    raise Exception(\"Answer to question 6 not found\")\n", "Exception: Answer to question 6 not found\n"], "q7": ["Traceback (most recent call last):\n", "  File \"/home/atrej/p2-a-team/tester.py\", line 28, in run\n    result = self.func()\n", "  File \"/home/atrej/p2-a-team/autograde.py\", line 111, in q7\n    raise Exception(\"Answer to question 7 not found\")\n", "Exception: Answer to question 7 not found\n"], "q8": ["Traceback (most recent call last):\n", "  File \"/home/atrej/p2-a-team/tester.py\", line 28, in run\n    result = self.func()\n", "  File \"/home/atrej/p2-a-team/autograde.py\", line 120, in q8\n    raise Exception(\"Answer to question 8 not found\")\n", "Exception: Answer to question 8 not found\n"], "q9": ["Traceback (most recent call last):\n", "  File \"/home/atrej/p2-a-team/tester.py\", line 28, in run\n    result = self.func()\n", "  File \"/home/atrej/p2-a-team/autograde.py\", line 129, in q9\n    raise Exception(\"Answer to question 9 not found\")\n", "Exception: Answer to question 9 not found\n"], "q10": ["Traceback (most recent call last):\n", "  File \"/home/atrej/p2-a-team/tester.py\", line 28, in run\n    result = self.func()\n", "  File \"/home/atrej/p2-a-team/autograde.py\", line 138, in q10\n    raise Exception(\"Answer to question 10 not found\")\n", "Exception: Answer to question 10 not found\n"]}}